{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-01T10:50:58Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.1.0
    sha: e13d3e03931a1cb361f6ec9808d58d0f018243e8
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 57a88ead574ee338f6ef5a398339ec2ec4e8cdd9
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      feat: config probes
    sha: 1824540b37d8e3ffc5b412bc262e4989327ac0bc
  gitHttpUrl: https://github.com/property-xyz/data-export-service
  gitOwner: property-xyz
  gitRepository: data-export-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-export-service/releases/tag/v0.2.0
  version: v0.2.0
status: {}
 
{{- end }}
