{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-26T17:07:07Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.2
    sha: a1b8de1c54f30a303d1db13e58b564357398e699
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 43c58345c587f4fd2094d4c40eaab521e244d007
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      fix: host name
    sha: 7b6b6931263491a708cba1f57da75698252e9256
  gitHttpUrl: https://github.com/property-xyz/data-search-service
  gitOwner: property-xyz
  gitRepository: data-search-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-search-service/releases/tag/v0.1.0
  version: v0.1.0
status: {}
 
{{- end }}
