apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template  "name" .}}-rb
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name:  {{ template  "name" .}}-role
subjects:
  - kind: ServiceAccount
    name: {{ template  "name" .}}-sa